services:
  coredns:
    build: .
    # image: coredns:latest
    # ports:
    #   - "53:53/udp"
    #   - "53:53/tcp"
    volumes:
      - ./Corefile:/etc/coredns/Corefile
    command: ["/coredns", "-conf", "/etc/coredns/Corefile"]
    networks:
      - coredns
    restart: always
    depends_on:
      corednsdb:
        condition: service_healthy
  corednsdb:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: coredns
      MYSQL_USER: coredns
      MYSQL_PASSWORD: coredns
    volumes:
      - ./docker/mysql/initdb:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - coredns
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
  corednsadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: corednsdb
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8085:80"
    networks:
      - coredns
    restart: always
networks:
  coredns:
